language: node_js
sudo: false

node_js:
  - '4'

cache:
  directories:
    - "$HOME/.npm"

env:
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - npm install -g phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup

notifications:
  email: false
  slack:
    secure: PfW3p/uh4np2nLRrXwqv9EQtdFPzvfnFehvHVUkXgv5xdWDd+kSZaxXOBCj2108nm8CFh8Ku/zE8fnje3N8Fe4LMtfpGuOL81Jl+rvQKG8l+/8M4pe5TYdyaHF6VcxbUkCQppi2hiqqtCdie7faRAXZDb1PGw9pIZhFBU9LcHXhdeP5sMADBJh1zqDkvS3YZQn6Ox4HXA9Q2oJPwHnkg42sLMAprWbnD/uzq1TKouDu0GGxqK89czxPBCjBufLObb2qb60IlwdHAXSjs89OgQBZy1ithLZM5SCwV4Rhv5vCbrgF4TpwGtDNmu06W745+Cyfr0OOzAHW2GuydAQqyhKW+DNoxltFbXdSzqtoZJ34B6eErxxlbeQSNpwLV6wmc6z8O1x4/Z7cIcWvp7C8JOp9kCxm1276k7YbWoNl1+BjQ9YIKhWO0DGurPZmCl74gtDUkphU/AcZvB0k2arUoTj7u2P797Ic6T8T0dBA8RpGiRt1/u+CTm5REnbhZV5EvO8bvZS/OJ6znIvZ3gxAE1ZFZa03xA5QC3cr6Sy3ORTjpASU1tPzGndGbg+GFC4GAHzidYuy5amSF/AV1PHy+Q6a1x6uBw2WQ8ybFswD4/bHY5yiAou0xsOSGKDxZ6MMygghrD+K5lrJC0P49wiOc+wvOgAii6EGv2E5ILJCEn9g=

deploy:
  provider: npm
  email: ohnoesmyoreos@gmail.com
  api_key:
    secure: mp/AOOmeQ2VF/ttHpEun1+mNXDPKyjOwXMkCbg0YtgrjtA04W7xpkzlFYqtyi4kpUVHa8xZ3V1FvfnOqTtr1pejexxMIBf7SWidV04WSRaK/GqawGH8b0Y5cDrmn4wGozCoHMwfibZDPpRrf/Jr7KCMI5Unok+nB+JIzBa68i3k1VxsjaTmDx8vjbbVayO8PAjksNlma4cpIEhm3Jv43VkSWlLO+nCMcVnqXi3JxvRWg2Oi2yq3P+HWIvrE4bnKGYk2lJhZOffUMnVP4Pn59q32lQIEiSWec7hW4o0veMzaMwSZK+K1wohIDWuy+njz2kmhxIWfjOCOJPNuuBiu7pJWZCLr0pfcOG+4gsRkQHKy2tnljfu8gz/bb4dFJELdgTAD2UjGz3dEnLYSS7TjBfbvXQtg7BICbKg8YHyY1dFHs2B0edB920LxI+7iyeUjEbtPBrR8h8mn9R/wqy40EUqRhFwTjedUqOzkXPo2jT+11TVY9zdomPQhGr77POS+kzPfDmJcUpqCw0rDaQT0lwfyFJbqzZqJTdUsw/S9fq1AXFn5kCG18HCpO38+QjRJNGXxsDOpQsrzck4PmhpTYt+jvS3EJLZIqDKYcxTRXbkge1KKY3aXbdOacvwoSb1+rAg1Rv82q6JFs7CVe8Gz+bdAelpFjbzwLxJ3AgtSDiH4=
  on:
    branch: master
    tags: true
